### ISSUE TITLE
Default Makefile insufficient on x64 architectures

### ISSUE THREAD

**Issue by robinduckett** [karthick18/inception#1]
In order to compile for x64 architectures the CFLAGS in the Makefile must be changed from -m32 to -m64.

**Comment by karthick18** [comment]
I had intentionally disabled builds for 64 bit since the morphing code buffer in inception.h just exits out _without_ writing Fischer's inception string as the last output in the screen before the code exits. So I will have to see why that last output isn't displayed in x86_64 which is Fischer's inception thought displayed correctly in x86. Anyway I would fix the build for x86_64 maybe with a warning that you need to run it with -m32 on x86_64 and If you are on Ubuntu, you install the libc6-dev-i386 package to compile with -m32 and run the code.

**Comment by karthick18** [comment]
Fixed with the last commit. Pull the latest for building on 64 bit.

**Comment by robinduckett** [comment]
Cool :D
